sonar.projectKey=dev-harshit-afk_pizza-express-auth-service
sonar.organization=dev-harshit-afk

sonar.projectName=pizza-express-auth-service

sonar.sources=src

sonar.tests=tests

sonar.exclusions=**/node_modules/**/*, **/dist/**/*, **/build/**/*, **/migration/**/*

sonar.qualitygate.wait=true

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.scm.exclusions.disabled=true